### ISSUE TITLE
Not Working on Cordova Electron

### ISSUE THREAD

**Issue by erwinyusrizal** [darkylmnx/vue-youtube-iframe-api#1]
I use this plugin to run youtube iframe on electron app, but seems the YT API instance not created, I got error:

```
[Vue warn]: Error in callback for watcher "ytid": "TypeError: this.player[method] is not a function"

TypeError: this.player[method] is not a function
    at VueComponent.loadById (Player.js:84)
    at VueComponent.ytid (Player.js:37)
```

any idea?

**Comment by ghost** [comment]
@erwinyusrizal it must be a CSP issue, check that :
https://stackoverflow.com/questions/51969512/define-csp-http-header-in-electron-app
https://github.com/vuejs/vue-devtools/issues/616#issuecomment-479549050

hope it helps

**Comment by darkylmnx** [comment]
Closing this since no news on it.
